export const FETCH_USER_INIT = 'FETCH_USER_INIT';
export const FETCH_USER_START = 'FECTH_USER_START';
export const FETCH_USER_SUCCESS = 'FECTH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FECTH_USER_FAIL';

export const UPDATE_SEGURO_SUCCESS = 'UPDATE_SEGURO_SUCCESS';
export const UPDATE_SEGURO_FAIL = 'UPDATE_SEGURO_FAIL';